[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "fontconfig", "dejavu_fonts", "liberation_ttf"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "python main.py"
